"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
[ÓÇ∂](color_orange)\
$os\
$username\
$hostname\
[ÓÇ∞](bg:color_lavender fg:color_orange)\
${custom.devpod}\
[ÓÇ∞](bg:color_pink fg:color_lavender)\
$directory\
[ÓÇ∞](fg:color_pink bg:color_bg1)\
$git_branch\
$git_status\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_fg0 = '#cad3f5'
color_bg1 = '#1e2030'
color_bg3 = '#24273a'
color_blue = '#8aadf4'
color_aqua = '#94e2d5'
color_green = '#a6e3a1'
color_orange = '#f5a97f'
color_purple = '#c6a0f6'
color_lavender = '#b4befe'
color_red = '#ed8796'
color_yellow = '#eed49f'
color_grey = '#585b70'
color_maroon = '#eba0ac'
color_pink = '#f5c2e7'
color_text = '#585b70'

[custom.devpod]
description = "Displays the active Devpod workspace"
command = "echo $(echo $DEVPOD_WORKSPACE_ID | sed 's/.*://')"
when = "[[ -n $DEVPOD_WORKSPACE_ID ]]"
style = "bold bg:color_lavender fg:color_text"
format = "[ üì¶ $output ]($style)"
disabled = false

[os]
disabled = false
style = "bold bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Û∞£á"
Artix = "Û∞£á"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"

[username]
show_always = true
style_user = "bold bg:color_orange fg:color_text"
style_root = "bold bg:color_orange fg:color_text"
format = '[ $user ]($style)'

[hostname]
ssh_only = true
format = '[$ssh_symbol : $hostname](bold bg:color_orange fg:color_text)'
disabled = false

[directory]
style = "bold fg:color_text bg:color_pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "
"Developer" = "Û∞≤ã "

[git_branch]
symbol = "Ôêò"
style = "bg:color_bg1"
format = '[[ $symbol $branch ](bold fg:color_green bg:color_bg1)]($style)'

[git_status]
style = "bold bg:color_bg1"
format = '[[($all_status$ahead_behind )](bold fg:color_green bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[‚ùØ](bold fg:color_green)'
error_symbol = '[‚ùØ](bold fg:color_red)'
vimcmd_symbol = '[‚ùÆ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[‚ùÆ](bold fg:color_purple)'
vimcmd_replace_symbol = '[‚ùÆ](bold fg:color_purple)'
vimcmd_visual_symbol = '[‚ùÆ](bold fg:color_yellow)'
